apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello-app
spec:
  components:
    - name: hello-app
      type: webservice
      properties:
        env:
          - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: hello-app
                key: MANAGEMENT_OTLP_TRACING_ENDPOINT
          - name: PYROSCOPE_URL
            valueFrom:
              configMapKeyRef:
                name: hello-app
                key: PYROSCOPE_URL
        image: sselzer/hello-app
        port: 8080
      traits:
        - type: labels
          properties:
            "app.kubernetes.io/name": "hello-app"
        - type: annotations
          properties:
            "prometheus.io/scrape": "true"
            "prometheus.io/path": /actuator/prometheus
            "prometheus.io/port": "8080"
        - type: cpuscaler
          properties:
            min: 1
            max: 3
            cpuPercent: 80
