apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - configuration.yaml
resources:
  - app.yaml
configMapGenerator:
  - name: hello-app
    literals:
      - "PYROSCOPE_URL=http://pyroscope.observability:4040"
      - "MANAGEMENT_OTLP_TRACING_ENDPOINT=http://tempo.observability:4318/v1/traces"
