apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hello-app"
  annotations:
    github.com/project-slug: "devops-syndicate/hello-app"
    argocd/app-name: hello-app
    backstage.io/kubernetes-namespace: hello-app
    backstage.io/kubernetes-id: hello-app
    backstage.io/kubernetes-label-selector: 'app.oam.dev/name=hello-app'
    backstage.io/techdocs-ref: dir:.
  links:
  - title: Link to ArgoCD
    url: http://argo-cd.127.0.0.1.nip.io/applications/hello-app
  tags:
  - java
  - spring-boot
spec:
  type: service
  owner: team-a
  lifecycle: production
  providesApis:
  - hello-app-api
